# Generated by Django 6.0.3 on 2026-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("can_block_user", "Can block user")]},
        ),
    ]
