# Generated by Django 6.0.3 on 2026-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255, verbose_name="Тема письма")),
                ("text", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["subject"],
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"ordering": ["pk"], "verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
    ]
