# Generated by Django 6.0.3 on 2026-04-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={"ordering": ["pk"], "verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время первой отправки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("running", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailing.message", verbose_name="Сообщение"
                    ),
                ),
                ("recipient", models.ManyToManyField(to="mailing.recipient", verbose_name="Получатели")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
