# Generated by Django 6.0.3 on 2026-04-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_recipient_options_mailing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="recipient",
            new_name="recipients",
        ),
    ]
