# Generated by Django 6.0.3 on 2026-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
